### ISSUE TITLE
app crash after compile seccusfully for android

### ISSUE THREAD

**Issue by Nillrze** [shigmas/PushApp#2]
Hi again
I used this code and it worked correctly till yesterday
Everything was fine. i compile project and install app several time
But now it doesn't work , it built but when install on the same android phone, it crashed

here is my application output

----------

W System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/FirebaseOptions$Builder;.setProjectId(Ljava/lang/String;)Lcom/google/firebase/FirebaseOptions$Builder;"
W System.err: 	at org.qtproject.qt5.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt5.android.QtNative$6.run(QtNative.java:359)
W System.err: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
W System.err: 	at java.lang.Thread.run(Thread.java:818)
W System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/FirebaseOptions;.getProjectId()Ljava/lang/String;"
W System.err: 	at org.qtproject.qt5.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt5.android.QtNative$6.run(QtNative.java:359)
W System.err: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
W System.err: 	at java.lang.Thread.run(Thread.java:818)
F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 21223 (qtMainLoopThrea)

"net.futomen.PushApp" died.

-----------

I checked every thing such as jdk , sdk , ndk , gradle
jdk vertion : 8u144
sdk version : 25.2.5 
ndk version: ndk-r10e

I try it on mac and linux both,  there was same problem
can you tell me what is my problem??
thanks a lot

**Comment by shigmas** [comment]
What does it say right before the stack trace? There is some debugging output that might point out which call is triggering the crash.

**Comment by GregoryError** [comment]
@Nillrze what was the solution?
